"""
Django settings for brandpulsar project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from django.urls import reverse_lazy
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h()$7&@g2xy+$9+4ph&g(8sz6^b(rov4^8cdf*$)mew^1x@f_&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['brandpulsar.com']

STRIPE_SECRET_KEY = 'sk_live_1a7XYNLaSJlRifq959qgGUUa00raNTCsge'
STRIPE_PUBLISHABLE_KEY = 'pk_live_3gD4r9HPQSJhjA9gwpfllJNF00T8vxHnYi'

STRIPE_INSTALMENT_WEBHOOK_ENPOINT_SECRET = 'whsec_QXop9bZRnUQsLZAeu3PcybDICFuqiJKw'
STRIPE_FEATURED_WEBHOOK_ENPOINT_SECRET = 'whsec_ix4J4i2vlIMH0mV3A8tXHgrHRqs1uMaS'

SENDGRID_API_KEY = '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'

BASE_URL = 'https://brandpulsar.com'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'channels',
    'main',
    'ckeditor',
    'ckeditor_uploader',
    'mathfilters',
    'django_filters',
    'rest_framework',
    'treebeard',
    'pagination_bootstrap',
    'users',
    'marketplace',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pagination_bootstrap.middleware.PaginationMiddleware',
]

ROOT_URLCONF = 'brandpulsar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'main.context_processors.allow_bots',
                'main.context_processors.faqs_processor',
                'main.context_processors.industries_processor',
            ],
        },
    },
]

REDIS_HOST='redis'
REDIS_PORT=6379
REDIS_PASSWORD='1qvSgjrAIRAHqD2ZqdV1Ojzxw'


BROKER_URL='redis://:1qvSgjrAIRAHqD2ZqdV1Ojzxw@redis:6379/0'

AUTH_USER_MODEL = 'users.User'

# WSGI_APPLICATION = 'brandpulsar.wsgi.application'
ASGI_APPLICATION = "brandpulsar.routing.application"


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(
                os.environ.get('REDIS_HOST', 'localhost'),
                os.environ.get('REDIS_PORT', 6379)
            )],
        },
    },
}



# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'brandpulsar/static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media-root")

CKEDITOR_UPLOAD_PATH = 'media/ckeditor_uploads/'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 24,
}


# Celery settings
# https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html


CELERY_BROKER_URL = os.environ.get(
    "BROKER_URL", "redis://:1qvSgjrAIRAHqD2ZqdV1Ojzxw@localhost:6379/0"
)

CELERY_TASK_IGNORE_RESULT = True
CELERY_TIMEZONE = TIME_ZONE


# Login url
LOGIN_URL = reverse_lazy('users:login-view')


# GoDaddy API Credentials
GODADDY_KEY = "dKiSnBoQsS47_XBZVJsJBisPPy7DEQGzYp2"
GODADDY_SECRET = "H1zWjPNVVustMgntHV58KQ"


# Date input forms
DATE_INPUT_FORMATS = ['%d-%m-%Y']


# Google OAUTH CREDENTIALS
GOOGLE_OAUTH_CLIENT_ID = "883270625790-i1rf30v76so056s1jjsjijivi4kc56tn.apps.googleusercontent.com"
GOOGLE_OAUTH_CLIENT_SECRET = "Cvr_3cfbAQRu5oYcrbhDycR5"


try:
    from .settings_local import *

    print('RUNNING WITH LOCAL SETTINGS')
except ImportError:
    print('LOCAL SETTINGS NOT FOUND. RUNNING WITH PRODUCTION SETTINGS')
    pass
