# Generated by Django 3.0.5 on 2021-01-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedDomainPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estimated Domain Price',
                'verbose_name_plural': 'Estimated Domain Prices',
            },
        ),
        migrations.CreateModel(
            name='DomainNegotiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Domain')),
            ],
            options={
                'verbose_name': 'Domain Negotiation',
                'verbose_name_plural': 'Domain Negotiations',
            },
        ),
        migrations.CreateModel(
            name='BrainstormingKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Main Key')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('industry', models.ManyToManyField(blank=True, to='main.Industry')),
            ],
            options={
                'verbose_name': 'Brainstorming Key',
                'verbose_name_plural': 'Brainstorming Keys',
            },
        ),
    ]
