# Generated by Django 3.0.5 on 2021-01-03 15:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Author uuid')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('position', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Position')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=main.utils.get_file_path, verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BankWire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Phone Number')),
                ('company', models.CharField(max_length=100, null=True, verbose_name='Company')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='State / Province')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('zip', models.CharField(max_length=100, null=True, verbose_name='Zip code')),
            ],
            options={
                'verbose_name': 'Bank Wire Form',
                'verbose_name_plural': 'Contact Forms',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Category display title')),
                ('description', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Category description')),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Category slug')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Blog post title')),
                ('metadescription', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('thumbnail_image', models.FileField(upload_to='posts/%Y/%m/%d/', verbose_name='Thumbnail image')),
                ('slug', models.SlugField(blank=True, default=None, max_length=550, null=True, verbose_name='Post slug')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('message', models.TextField(max_length=100, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail address')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=60, verbose_name='Surname')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('industry', models.CharField(blank=True, max_length=250, null=True, verbose_name='Industry')),
                ('employees', models.CharField(blank=True, choices=[('0-50', '0-50'), ('50-100', '50-100'), ('100-150', '100-150'), ('150-200', '150-200'), ('200-250', '200-250')], max_length=150, verbose_name='Employees')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='Quote')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('thumbnail_image', models.FileField(upload_to='customers/%Y/%m/%d/', verbose_name='Thumbnail image')),
                ('slug', models.SlugField(blank=True, default=None, max_length=550, null=True, verbose_name='Slug')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Domain name')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Domain length')),
                ('is_active', models.CharField(choices=[('waiting', 'WAITING'), ('pending', 'PENDING'), ('listed', 'LISTED')], default='waiting', max_length=10)),
                ('extension', models.CharField(max_length=150, null=True, verbose_name='Domain extension')),
                ('stripe_recurring_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Recurring product id')),
                ('stripe_one_time_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='One time product id')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Discount Price')),
                ('negotiable_price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Negotiable Domain price')),
                ('favorite_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Favorite Count')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('domain_length', models.CharField(blank=True, choices=[('bad', 'bad'), ('poor', 'poor'), ('fair', 'fair'), ('good', 'good'), ('excellent', 'excellent')], max_length=150, verbose_name='Domain length rating')),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('sold', 'SOLD')], default='available', max_length=25, verbose_name='Status of the domain')),
                ('pronouncement', models.CharField(blank=True, choices=[('bad', 'bad'), ('poor', 'poor'), ('fair', 'fair'), ('good', 'good'), ('excellent', 'excellent')], default='available', max_length=150, verbose_name='Domain pronouncement rating')),
                ('brandable', models.CharField(blank=True, choices=[('bad', 'bad'), ('poor', 'poor'), ('fair', 'fair'), ('good', 'good'), ('excellent', 'excellent')], max_length=150, verbose_name='Domain brandable rating')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='domains/%Y/%m/%d/', verbose_name='Thumbnail image')),
                ('mockup_1', models.FileField(blank=True, null=True, upload_to='mockups/%Y/%m/%d/', verbose_name='Mockup 1')),
                ('syllable', models.PositiveIntegerField(blank=True, null=True, verbose_name='Syllable count')),
                ('mockup_2', models.FileField(blank=True, null=True, upload_to='mockups/%Y/%m/%d/', verbose_name='Mockup 2')),
                ('mockup_3', models.FileField(blank=True, null=True, upload_to='mockups/%Y/%m/%d/', verbose_name='Mockup 3')),
                ('slug', models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True, verbose_name='Domain slug')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='Visitor Count')),
                ('stripe_product_id', models.CharField(blank=True, max_length=120, null=True)),
                ('featured_plan_id', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Industry name')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('icon', models.FileField(blank=True, null=True, upload_to='industries/%Y/%m/%d/', verbose_name='Icon')),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Industry slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Domain tag title')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Plan Nickname')),
                ('unit_amount', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='Price per unit')),
                ('plan_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plan ID')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='main.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='industry',
            field=models.ManyToManyField(blank=True, related_name='industry', to='main.Industry', verbose_name='Industries'),
        ),
    ]
